version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    restart: on-failure
    command: sh -c "npm run start:dev"

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client:/usr/share/nginx/html
    restart: on-failure

  redis:
    image: redis:alpine
    restart: on-failure
